// frontend/src/screens/ProjectsScreenStyles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7fafc',
  },
  header: {
    backgroundColor: '#3182ce',
    padding: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  subtitle: {
    fontSize: 14,
    color: '#e2e8f0',
  },
  content: {
    padding: 16,
  },
  formContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    marginTop: 12,
    marginBottom: 4,
  },
  optional: {
    color: '#4299e1',
    marginTop: 24,
  },
  input: {
    height: 45,
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    fontSize: 16,
  },
  select: {
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 4,
    marginBottom: 8,
  },
  textarea: {
    height: 100,
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingTop: 8,
    fontSize: 16,
    textAlignVertical: 'top',
    marginBottom: 8,
  },
  errorInput: {
    borderColor: '#f56565',
  },
  errorText: {
    color: '#f56565',
    fontSize: 12,
    marginBottom: 8,
  },
  submitButton: {
    backgroundColor: '#4299e1',
    borderRadius: 4,
    padding: 15,
    alignItems: 'center',
    marginTop: 24,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  resultsContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  resultsSubtitle: {
    color: '#4a5568',
    marginBottom: 16,
  },
  loadingContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#4a5568',
  },
  loadingSubtext: {
    marginTop: 8,
    fontSize: 12,
    color: '#718096',
    textAlign: 'center',
  },
  ideaCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  ideaTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4299e1',
    marginBottom: 8,
  },
  ideaDescription: {
    color: '#4a5568',
    marginBottom: 16,
  },
  ideaButtons: {
    flexDirection: 'row',
  },
  ideaButton: {
    backgroundColor: '#ebf8ff',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginRight: 8,
  },
  greenButton: {
    backgroundColor: '#f0fff4',
  },
  ideaButtonText: {
    color: '#4299e1',
    fontSize: 12,
  },
  moreIdeasButton: {
    backgroundColor: '#4299e1',
    borderRadius: 4,
    padding: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  moreIdeasButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  emptyContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  emptyText: {
    color: '#4a5568',
    textAlign: 'center',
    marginTop: 8,
  },
  reportContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    flex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginHorizontal: 16,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  reportTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4299e1',
    flex: 1,
  },
  backButton: {
    color: '#718096',
  },
  reportSection: {
    marginBottom: 24,
  },
  reportSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  reportText: {
    lineHeight: 24,
    color: '#4a5568',
  },
  reportListItem: {
    marginBottom: 8,
    paddingLeft: 12,
    lineHeight: 22,
    color: '#4a5568',
  },
  reportActions: {
    marginVertical: 24,
    alignItems: 'center',
  },
  reportButton: {
    backgroundColor: '#48bb78',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  reportButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  footer: {
    backgroundColor: '#f7fafc',
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  footerText: {
    color: '#718096',
    fontSize: 12,
  },
});
export default styles;